[phases.setup]
nixPkgs = ["php83", "php83Extensions.pdo", "php83Extensions.pdo_mysql", "php83Extensions.mbstring", "php83Extensions.intl", "php83Extensions.opcache", "php83Extensions.xml", "php83Extensions.curl", "php83Extensions.zip"]